/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface VotingInterface extends utils.Interface {
  functions: {
    "candidates(uint256)": FunctionFragment;
    "candidatesCount()": FunctionFragment;
    "getVotes(uint256)": FunctionFragment;
    "vote(uint256,address)": FunctionFragment;
    "voters(address)": FunctionFragment;
    "winningCandidate()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "candidates"
      | "candidatesCount"
      | "getVotes"
      | "vote"
      | "voters"
      | "winningCandidate"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "candidates",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "candidatesCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVotes",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "voters",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "winningCandidate",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "candidates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "candidatesCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVotes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "winningCandidate",
    data: BytesLike
  ): Result;

  events: {
    "VotedEvent(uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "VotedEvent"): EventFragment;
}

export interface VotedEventEventObject {
  _candidateId: BigNumber;
  _voter: string;
}
export type VotedEventEvent = TypedEvent<
  [BigNumber, string],
  VotedEventEventObject
>;

export type VotedEventEventFilter = TypedEventFilter<VotedEventEvent>;

export interface Voting extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VotingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    candidates(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        id: BigNumber;
        name: string;
        voteCount: BigNumber;
      }
    >;

    candidatesCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getVotes(
      _candidateId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    vote(
      _candidateId: PromiseOrValue<BigNumberish>,
      _voter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    voters(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    winningCandidate(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  candidates(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber] & {
      id: BigNumber;
      name: string;
      voteCount: BigNumber;
    }
  >;

  candidatesCount(overrides?: CallOverrides): Promise<BigNumber>;

  getVotes(
    _candidateId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  vote(
    _candidateId: PromiseOrValue<BigNumberish>,
    _voter: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  voters(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  winningCandidate(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    candidates(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber] & {
        id: BigNumber;
        name: string;
        voteCount: BigNumber;
      }
    >;

    candidatesCount(overrides?: CallOverrides): Promise<BigNumber>;

    getVotes(
      _candidateId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vote(
      _candidateId: PromiseOrValue<BigNumberish>,
      _voter: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    voters(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    winningCandidate(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "VotedEvent(uint256,address)"(
      _candidateId?: PromiseOrValue<BigNumberish> | null,
      _voter?: null
    ): VotedEventEventFilter;
    VotedEvent(
      _candidateId?: PromiseOrValue<BigNumberish> | null,
      _voter?: null
    ): VotedEventEventFilter;
  };

  estimateGas: {
    candidates(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    candidatesCount(overrides?: CallOverrides): Promise<BigNumber>;

    getVotes(
      _candidateId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vote(
      _candidateId: PromiseOrValue<BigNumberish>,
      _voter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    voters(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    winningCandidate(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    candidates(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    candidatesCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getVotes(
      _candidateId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vote(
      _candidateId: PromiseOrValue<BigNumberish>,
      _voter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    voters(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    winningCandidate(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
